### ISSUE TITLE
Исправления whois

### ISSUE THREAD

**Issue by tm-minty** [Ganza6/shell-script#1]
Денис, переделай url проверки на https://www.whois.com/whois/DOMAIN, как указано в задании.
Из проверяемых доменов нужно убирать все ненужное, чтобы проверялось только доменное имя 2-го уровня
+ какие-то проблемы с кодировкой

**Comment by Ganza6** [comment]
> Из проверяемых доменов нужно убирать все ненужное, чтобы проверялось только доменное имя 2-го уровня

К каждому домену 2 уровня, введённому без домена первого уровня, автоматически добавляется домен первого уровня .com. То есть, если я всё правильно понимаю, проверить только доменное имя 2-го уровня невозможно.

Если же всё таки отправлять на сервер запрос с доменным именем второго уровня, отсекая доменное имя первого уровня, то может возникнуть ситуация, когда пользователь ввёл домен "yandex.ru", а скрипт предоставил ему информацию по домену "yandex.com". Поэтому непонятно нужно ли всегда игнорировать домен первого уровня введённый пользователем или всё же нужно и его(домен первого уровня) внести в запрос.
